name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Or your chosen branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "$EC2_KEY" > private_key.pem
          chmod 600 private_key.pem
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Ensure the directory exists
            sudo mkdir -p /var/www/awsfinal
            sudo chown -R $USER:$USER /var/www/awsfinal

            # Deploy the repo
            if [ -d "/var/www/awsfinal/.git" ]; then
              cd /var/www/awsfinal
              git pull origin main
            else
              git clone https://github.com/notesMafia/awsfinal.git /var/www/awsfinal
            fi

            echo "✅ Code deployed to /var/www/awsfinal"
          EOF
